### ISSUE TITLE
Migrate repository to go-enry org

### ISSUE THREAD

**Issue by lafriks** [src-d/go-license-detector#71]
Or under new organization but probably go-enry topic is closely related so they could be in same org?

**Comment by vmarkovtsev** [comment]
It makes sense to switch the org, however, I don't have time for that right now (this year). If somebody mirrors the repository somewhere and makes me an owner then I will be happy to deprecate the current one.

**Comment by mcuadros** [comment]
I will

**Comment by mcuadros** [comment]
Done: https://github.com/go-enry/go-license-detector
I migrated everything to GitHub Actions and also I updated the go.mod. 

@vmarkovtsev I just invited you to the repository, It also will be great if you can take a look at the windows tests since it is failing (for some reason didn't fail at appveyor).
